from datetime import datetime

from .models import SOSPriority, SOSRecord, SOSStatus, SOSType

# Static demo dataset for the management panel PoC. Mobile app/API integration
# is out of scope for now; SOSRepository is the only place this is consumed,
# so swapping it for a real data source later won't touch the UI layer.
_SAMPLE_RECORDS = [
    dict(
        id="SOS-2023-0001",
        user_name="Ayşe Yılmaz",
        sos_type=SOSType.ENKAZ_ALTINDA,
        description="Hatay Antakya Cebrail Mahallesi'nde çöken apartmanın altındayız, ses verebiliyoruz.",
        location_label="Hatay / Antakya - Cebrail Mahallesi",
        priority=SOSPriority.KRITIK,
        status=SOSStatus.BEKLEMEDE,
        created_at=datetime(2023, 2, 6, 4, 32),
        latitude=36.2020,
        longitude=36.1610,
    ),
    dict(
        id="SOS-2023-0002",
        user_name="Mehmet Demir",
        sos_type=SOSType.ACIL_SAGLIK,
        description="Yaşlı annem göğüs ağrısı çekiyor, çadır alanında doktor gerekiyor.",
        location_label="Kahramanmaraş / Merkez - Şehir Stadı Çadır Alanı",
        priority=SOSPriority.KRITIK,
        status=SOSStatus.INCELENIYOR,
        created_at=datetime(2023, 2, 6, 6, 10),
        latitude=37.5740,
        longitude=36.9280,
    ),
    dict(
        id="SOS-2023-0003",
        user_name="Fatma Kaya",
        sos_type=SOSType.KURTARMA_TALEBI,
        description="Komşu binada 3 kişi mahsur kaldı, yıkım devam ediyor, ekip yönlendirin.",
        location_label="Gaziantep / Nurdağı - Cumhuriyet Caddesi",
        priority=SOSPriority.KRITIK,
        status=SOSStatus.YONLENDIRILDI,
        created_at=datetime(2023, 2, 6, 7, 45),
        latitude=37.0600,
        longitude=37.3800,
    ),
    dict(
        id="SOS-2023-0004",
        user_name="Ali Çelik",
        sos_type=SOSType.BARINMA,
        description="Evimiz kullanılamaz durumda, 5 kişilik aile için çadır ihtiyacımız var.",
        location_label="Malatya / Battalgazi Mahallesi",
        priority=SOSPriority.YUKSEK,
        status=SOSStatus.BEKLEMEDE,
        created_at=datetime(2023, 2, 6, 9, 15),
        latitude=38.3550,
        longitude=38.3050,
    ),
    dict(
        id="SOS-2023-0005",
        user_name="Zeynep Arslan",
        sos_type=SOSType.SU_IHTIYACI,
        description="Toplanma alanında 200'e yakın kişi var, içme suyu tükendi.",
        location_label="Adıyaman / Merkez Toplanma Alanı",
        priority=SOSPriority.ORTA,
        status=SOSStatus.YONLENDIRILDI,
        created_at=datetime(2023, 2, 6, 11, 0),
        latitude=37.7630,
        longitude=38.2760,
    ),
    dict(
        id="SOS-2023-0006",
        user_name="Mustafa Şahin",
        sos_type=SOSType.GIDA_IHTIYACI,
        description="Mahallemizde yollar kapalı, market erişimi yok, gıda kolisi bekliyoruz.",
        location_label="Hatay / İskenderun - Cumhuriyet Mahallesi",
        priority=SOSPriority.ORTA,
        status=SOSStatus.BEKLEMEDE,
        created_at=datetime(2023, 2, 6, 13, 20),
        latitude=36.5870,
        longitude=36.1720,
    ),
    dict(
        id="SOS-2023-0007",
        user_name="Elif Yıldız",
        sos_type=SOSType.ENKAZ_ALTINDA,
        description="Çökmüş binadan sesler geliyor, arama kurtarma ekibi hâlâ ulaşmadı.",
        location_label="Kahramanmaraş / Onikişubat - Yörükselim Mahallesi",
        priority=SOSPriority.KRITIK,
        status=SOSStatus.INCELENIYOR,
        created_at=datetime(2023, 2, 6, 15, 5),
        latitude=37.5900,
        longitude=36.9370,
    ),
    dict(
        id="SOS-2023-0008",
        user_name="Hüseyin Aydın",
        sos_type=SOSType.ACIL_SAGLIK,
        description="Enkazdan çıkarılan yaralı için ambulans talep ediyoruz.",
        location_label="Adana / Seyhan - Türkocağı Mahallesi",
        priority=SOSPriority.YUKSEK,
        status=SOSStatus.COZULDU,
        created_at=datetime(2023, 2, 6, 17, 40),
        latitude=37.0000,
        longitude=35.3213,
    ),
    dict(
        id="SOS-2023-0009",
        user_name="Emine Koç",
        sos_type=SOSType.DIGER,
        description="Elektrik ve iletişim kesik, jeneratör veya powerbank ihtiyacı var.",
        location_label="Şanlıurfa / Akçakale İlçe Merkezi",
        priority=SOSPriority.DUSUK,
        status=SOSStatus.BEKLEMEDE,
        created_at=datetime(2023, 2, 7, 2, 15),
        latitude=37.1591,
        longitude=38.7969,
    ),
    dict(
        id="SOS-2023-0010",
        user_name="İbrahim Polat",
        sos_type=SOSType.KURTARMA_TALEBI,
        description="Çift katlı evin bodrumunda 2 çocuk mahsur, acil ekip lazım.",
        location_label="Malatya / Yeşilyurt - Fatih Mahallesi",
        priority=SOSPriority.KRITIK,
        status=SOSStatus.YONLENDIRILDI,
        created_at=datetime(2023, 2, 7, 4, 50),
        latitude=38.3300,
        longitude=38.2600,
    ),
    dict(
        id="SOS-2023-0011",
        user_name="Sultan Aktaş",
        sos_type=SOSType.BARINMA,
        description="Bebekli aile olarak dışarıda kaldık, kapalı barınma alanına ihtiyacımız var.",
        location_label="Adıyaman / Kahta İlçesi",
        priority=SOSPriority.YUKSEK,
        status=SOSStatus.INCELENIYOR,
        created_at=datetime(2023, 2, 7, 8, 30),
        latitude=37.7854,
        longitude=38.6386,
    ),
    dict(
        id="SOS-2023-0012",
        user_name="Osman Yalçın",
        sos_type=SOSType.SU_IHTIYACI,
        description="Şebeke suyu kesildi, yaklaşık 40 haneye içme suyu ulaştırılmalı.",
        location_label="Diyarbakır / Sur İlçesi",
        priority=SOSPriority.ORTA,
        status=SOSStatus.COZULDU,
        created_at=datetime(2023, 2, 7, 10, 5),
        latitude=37.9144,
        longitude=40.2306,
    ),
    dict(
        id="SOS-2023-0013",
        user_name="Derya Şen",
        sos_type=SOSType.GIDA_IHTIYACI,
        description="Çadır kentte hazır gıda ve bebek maması stoku bitti.",
        location_label="Osmaniye / Merkez Çadır Kenti",
        priority=SOSPriority.ORTA,
        status=SOSStatus.BEKLEMEDE,
        created_at=datetime(2023, 2, 7, 12, 45),
        latitude=37.0742,
        longitude=36.2478,
    ),
    dict(
        id="SOS-2023-0014",
        user_name="Kemal Doğan",
        sos_type=SOSType.ACIL_SAGLIK,
        description="Kronik rahatsızlığı olan bir hasta için ilaç ve tıbbi destek gerekiyor.",
        location_label="Elazığ / Merkez - Rızaiye Mahallesi",
        priority=SOSPriority.YUKSEK,
        status=SOSStatus.INCELENIYOR,
        created_at=datetime(2023, 2, 7, 15, 30),
        latitude=38.6810,
        longitude=39.2264,
    ),
    dict(
        id="SOS-2023-0015",
        user_name="Aylin Er",
        sos_type=SOSType.ENKAZ_ALTINDA,
        description="6 katlı binanın altında kalan komşularımız için kurtarma bekliyoruz.",
        location_label="Hatay / Defne İlçesi",
        priority=SOSPriority.KRITIK,
        status=SOSStatus.BEKLEMEDE,
        created_at=datetime(2023, 2, 8, 1, 20),
        latitude=36.1460,
        longitude=36.1590,
    ),
    dict(
        id="SOS-2023-0016",
        user_name="Yusuf Kurt",
        sos_type=SOSType.DIGER,
        description="Bölgeye ulaşım için yol açma ve iş makinesi desteği talep ediyoruz.",
        location_label="Kahramanmaraş / Elbistan İlçesi",
        priority=SOSPriority.ORTA,
        status=SOSStatus.YONLENDIRILDI,
        created_at=datetime(2023, 2, 8, 6, 55),
        latitude=38.2010,
        longitude=37.1970,
    ),
    dict(
        id="SOS-2023-0017",
        user_name="Merve Bulut",
        sos_type=SOSType.BARINMA,
        description="Konteyner kent kurulana kadar geçici çadır talebimiz var.",
        location_label="Gaziantep / İslahiye İlçesi",
        priority=SOSPriority.DUSUK,
        status=SOSStatus.COZULDU,
        created_at=datetime(2023, 2, 8, 9, 40),
        latitude=37.0250,
        longitude=36.6350,
    ),
    dict(
        id="SOS-2023-0018",
        user_name="Serkan Avcı",
        sos_type=SOSType.KURTARMA_TALEBI,
        description="Yol kapalı olduğu için ekip bölgeye ulaşamıyor, alternatif güzergah gerekiyor.",
        location_label="Malatya / Doğanşehir İlçesi",
        priority=SOSPriority.YUKSEK,
        status=SOSStatus.IPTAL_EDILDI,
        created_at=datetime(2023, 2, 8, 13, 15),
        latitude=38.0960,
        longitude=37.8830,
    ),
    dict(
        id="SOS-2023-0019",
        user_name="Gül Öztürk",
        sos_type=SOSType.SU_IHTIYACI,
        description="İçme suyu tankeri son 2 gündür bölgeye uğramadı, stok bitti.",
        location_label="Adıyaman / Gölbaşı İlçesi",
        priority=SOSPriority.ORTA,
        status=SOSStatus.BEKLEMEDE,
        created_at=datetime(2023, 2, 9, 5, 25),
        latitude=37.7770,
        longitude=37.6390,
    ),
    dict(
        id="SOS-2023-0020",
        user_name="Tolga Uçar",
        sos_type=SOSType.ACIL_SAGLIK,
        description="Solunum cihazına bağlı bir hasta için elektrik/jeneratör desteği acil.",
        location_label="Şanlıurfa / Siverek İlçesi",
        priority=SOSPriority.KRITIK,
        status=SOSStatus.INCELENIYOR,
        created_at=datetime(2023, 2, 9, 8, 10),
        latitude=37.7524,
        longitude=39.3168,
    ),
]


def get_sample_sos_records() -> list[SOSRecord]:
    return [SOSRecord(**fields) for fields in _SAMPLE_RECORDS]
